cart/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('cart.views',
                       url(r'^$', 'show_cart', {'template_name': 'cart/cart.html'}, 'show_cart'),

)

ecomstore/urls.py
import os
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()
urlpatterns = patterns('',
                       # Examples:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^', include('catalog.urls')),
                       url(r'^cart/', include('cart.urls')),
                       url(r'^checkout/', include('checkout.urls')),
                       url(r'^accounts/', include('accounts.urls')),
                       url(r'^accounts/', include('django.contrib.auth.urls')),
                       url(r'^search/', include('search.urls')),
)

handler404 = 'ecomstore.views.file_not_found_404'

search/models.py
from django.contrib.auth.models import User
from django.db import models

class SearchTerm(models.Model):
    q = models.CharField(max_length=50)
    search_date = models.DateTimeField(auto_now_add=True)
    tracking_id = models.CharField(max_length=50, default='')
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null=True )

    def __unicode__(self):
        return self.q

templates/tags/cart_box.html
{% with cart_item_count as cart_count %}
        <a href="{% url "show_cart" %}">
            Shopping Cart
            <br />
            {{ cart_count }} Item{{ cart_count|pluralize }}
        </a>
{% endwith %}

templates/tags/category_list.html
<br />
<br />
        <h2>Categories</h2>
<ul id="categories">
    {% with active_categories as categories %}
    {% for category in categories %}
        {% ifequal category.get_absolute_url request_path %}
        <a href="{{category.get_absolute_url}}" class="list-group-item">{{category.name}}</a>
        {% else %}
        <a href="{{category.get_absolute_url}}" class="list-group-item">{{category.name}}</a>
        {% endifequal %}
    {% endfor %}
    {% endwith %}
</ul>

templates/tags/footer.html
<a href="{% url "catalog_home" %}">Home</a>
{% with flatpage_list as pages %}
        {% for page in pages %}
        <a href="{{page.url}}">{{page.title}}</a>
        {% endfor %}
{% endwith %}
<a href="{% url "show_cart" %}">Shopping Cart</a>

templates/tags/form_table_row.html
<tr>
    <th>
        {% if form_field.field.required %}
            *
        {% endif %}
        {{ form_field.label_tag }}
    </th>
    <td>
        {% if form_field.errors %}
            <ul class="errorlist">
                {% for error in form_field.errors %}
                    <li>{{ form_field.label }}: {{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {{ form_field }}
    </td>
</tr>

templates/tags/navigation.html
{% load catalog_tags %}

<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Online Shop</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="/catalog">About</a></li>
                <li><a href="/catalog">Privacy</a></li>
                <li><a href="/catalog">Products</a></li>
                <li><a href="/contact/">Contact</a></li>

                <li>
                    <a href="{% url "my_account" %}">My Account</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url "django.contrib.auth.views.logout" %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url "register" %}">Sign up</a>
                </li>
                <li>
                    <a href="{% url "django.contrib.auth.views.login" %}">Login</a>
                </li>
                {% endif %}

                <li>
                    {% cart_box request %}
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

templates/tags/pagination_links.html
{% if p.has_other_pages %}
    {% if p.has_previous %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.previous_page_number }}">
            &laquo; Previous
        </a>
    {% else %}
        &laquo; Previous
    {% endif %}
    | Page {{ p.number }} of {{ paginator.num_pages }} |
    {% if p.has_next %}
        <a href="{{ request.path }}?{{ params }}&page={{ p.next_page_number }}">
            Next &raquo;
        </a>
    {% else %}
        Next &raquo;
    {% endif %}
{% endif %}

templates/tags/product_list.html
{% for product in products %}
{% if forloop.first %}
<div class="row">
    <h3>{{header_text}}</h3>
    {% endif %}
    {% include 'tags/product_thumbnail.html' %}
    {% if forloop.last %}
</div>
{% endif %}
{% endfor %}

templates/tags/product_thumbnail.html
{% load staticfiles %}
{% load catalog_filters %}


<div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <a href="{{ product.get_absolute_url }}">
            <img src="{% static product.thumbnail %}" alt="">
                </a>

            <div class="caption">
                <h4 class="pull-right">{{ product.price|currency }}</h4>
                <h4><a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                </h4>

                <p>{{product.description}}</p>
            </div>
        </div>
  </div>

templates/tags/search_box.html
<form id="search" action="{% url "search_results" %}" method="get">
    <h3><label for="id_q">Search</label> </h3>
   {{form.q}}
    <input type="submit" value="Search"/>
    </form>